version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    restart: always
    command: /bin/sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      python manage.py loaddata db &&
      gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      - db
